import Head from "next/head";
import { Inter } from "next/font/google";
import { GetStaticProps } from 'next'
import { ICommonTagsResult } from "music-metadata";
import { useEffect, useState } from "react";
import Image from 'next/image'

const inter = Inter({ subsets: ["latin"] });


type props = {
  song: ICommonTagsResult
}

export default function Home({ song }: props) {

  const [imgSrc, setImgSrc] = useState("")


  //@ts-ignore
  const imgData = song.picture![0].data["data"]

  useEffect(() => {

    let data: string = ""
    for (var i = 0; i < imgData.length; i++) {
      data += String.fromCharCode(imgData[i]);
    }

    setImgSrc(`data:image/jpeg;base64,${btoa(data)}`)
    return () => {

    }
  }, [])


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>el titulo es {song.title}</div>
      <div>el formato de la imagen es {song.picture![0].format}</div>
      <Image src={imgSrc} alt="image" width={350} height={350} />
    </>)
}



export const getStaticProps = (async (context) => {

  const res = await fetch(process.env.API_URL!)
  const data: ICommonTagsResult = await res.json()

  return {
    props: {
      song: data
    }
  }
}) satisfies GetStaticProps<{
  song: ICommonTagsResult
}>